---
- name: Create group "someusers"
  ansible.builtin.group:
    name: someusers

- name: Create user by list
  ansible.builtin.user:
    name: "{{ item.login }}"
    password: "{{ item.pass | password_hash('sha512') }}"
    group: someusers
    home: "/home/someusers/{{ item.login }}"
  with_list: "{{ users }}"
  no_log: true
